---
blank_issues_enabled: false
contact_links:
  - name: Report security vulnerabilities in Kubara
    url: https://github.com/kubara-io/kubara/security/policy
    about: Please read here how you can report security vulnerabilities in Kubara.
